--
-- File generated with SQLiteStudio v3.3.3 on пн но€б. 8 14:45:30 2021
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: ACCOUNTS
CREATE TABLE ACCOUNTS (account_id INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR (255));

-- Table: CARDS
CREATE TABLE CARDS (card_id VARCHAR (45) PRIMARY KEY UNIQUE NOT NULL, pin VARCHAR (45) NOT NULL, sum DOUBLE NOT NULL, isActive BOOLEAN NOT NULL, user_id INTEGER REFERENCES ACCOUNTS (account_id) NOT NULL);

-- Table: TRANSACTIONS
CREATE TABLE TRANSACTIONS ("from" VARCHAR (45) REFERENCES CARDS NOT NULL, "to" VARCHAR (45) REFERENCES CARDS NOT NULL, sum DOUBLE NOT NULL, dateTime DATETIME NOT NULL, transaction_id INTEGER PRIMARY KEY NOT NULL UNIQUE);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
